## Q01

In [2]:
import numpy as np

arr = np.arange(1, 11)
print(f'Sum is {arr.sum()}\nMean is {arr.mean()}\nProduct is {arr.prod()}')

Sum is 55
Mean is 5.5
Product is 3628800


## Q02

In [22]:
mat = np.random.randint(1, 10 ,size = (3, 3))
t = np.transpose(mat)

print(f'Matrix:\n {mat}\nTranspose:\n {t}')


Matrix:
 [[1 3 8]
 [3 7 6]
 [5 3 4]]
Transpose:
 [[1 3 5]
 [3 7 3]
 [8 6 4]]


## Q03

In [24]:
arr = np.arange(1, 21)
arr_reshaped = arr.reshape(4, 5)

print(f'Array:\n{arr}\nReshape:\n{arr_reshaped}')


Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshape:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Q04

In [25]:
arr_1 = np.random.randint(1, 20, 8)
arr_2 = np.random.randint(1, 20, 8)

print("The first Array is: ", arr_1)
print("The second Array is: ", arr_2)

print(f"Addition: {np.add(arr_1, arr_2)}\nMultiplication: {np.multiply(arr_1, arr_2)}\nSubtraction: {np.subtract(arr_1, arr_2)}\nDivision: {np.divide(arr_1, arr_2)}\n")

The first Array is:  [16 19 13 11  1 10  2 17]
The second Array is:  [19 10 18  9  7 13 17 11]
Addition: [35 29 31 20  8 23 19 28]
Multiplication: [304 190 234  99   7 130  34 187]
Subtraction: [ -3   9  -5   2  -6  -3 -15   6]
Division: [0.84210526 1.9        0.72222222 1.22222222 0.14285714 0.76923077
 0.11764706 1.54545455]



## Q05

In [8]:
nums = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
arr = np.sqrt(nums)

print(f'Original Array:{nums}')
arr

Original Array:[  1   4   9  16  25  36  49  64  81 100]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Q06

In [45]:
matrix = np.random.randint(1, 10 ,size = (2, 2))
det = int(np.linalg.det(matrix))
print(matrix)

if det == 0:
    print(f'determinant:{det} hence zero inverse doesnt exist')
else:
    print(f'determinant:{det}\nInverse:\n{np.linalg.inv(matrix)}')

[[7 9]
 [4 9]]
determinant:27
Inverse:
[[ 0.33333333 -0.33333333]
 [-0.14814815  0.25925926]]


## Q07

In [57]:
arr = np.random.randint(1, 10000 ,50)

print(f'max index = {np.argmax(arr)}\nmin index = {np.argmin(arr)}')

max index = 41
min index = 48


## Q08

In [66]:
coefficent_mat = np.array([[2, 4, 9],[1, 9, 7],[3, 8, 7]])
const_mat = np.array([2, 3, 5])

np.linalg.solve(coefficent_mat, const_mat)

array([ 1.17821782,  0.35643564, -0.1980198 ])

## Q09

In [67]:
arr = np.random.randint(1, 10000 ,25)

np.percentile(arr, 75)

8116.0

## Q10

In [112]:
def normalize_array(array):
    mean = np.mean(arr)
    std_deviation = np.std(arr)
    
    return np.divide((np.subtract(arr, mean)), std_deviation)

arr = np.random.randint(1, 100, 5)
print(f'Array = {arr}\nNormalized:{normalize_array(arr)}')


Array = [29 52 16 15 87]
Normalized:[-0.39837484  0.45001602 -0.87790011 -0.91478667  1.7410456 ]
