## Q01

In [5]:
import numpy as np

arr = np.arange(1, 11)
print(f'Sum is {arr.sum()}\nMean is {arr.mean()}\nProduct is {arr.prod()}')

Sum is 55
Mean is 5.5
Product is 3628800


## Q02

In [22]:
mat = np.random.randint(1, 10 ,size = (3, 3))
t = np.transpose(mat)

print(f'Matrix:\n {mat}\nTranspose:\n {t}')


Matrix:
 [[1 3 8]
 [3 7 6]
 [5 3 4]]
Transpose:
 [[1 3 5]
 [3 7 3]
 [8 6 4]]


## Q03

In [24]:
arr = np.arange(1, 21)
arr_reshaped = arr.reshape(4, 5)

print(f'Array:\n{arr}\nReshape:\n{arr_reshaped}')


Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshape:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Q04

In [25]:
arr_1 = np.random.randint(1, 20, 8)
arr_2 = np.random.randint(1, 20, 8)

print("The first Array is: ", arr_1)
print("The second Array is: ", arr_2)

print(f"Addition: {np.add(arr_1, arr_2)}\nMultiplication: {np.multiply(arr_1, arr_2)}\nSubtraction: {np.subtract(arr_1, arr_2)}\nDivision: {np.divide(arr_1, arr_2)}\n")

The first Array is:  [16 19 13 11  1 10  2 17]
The second Array is:  [19 10 18  9  7 13 17 11]
Addition: [35 29 31 20  8 23 19 28]
Multiplication: [304 190 234  99   7 130  34 187]
Subtraction: [ -3   9  -5   2  -6  -3 -15   6]
Division: [0.84210526 1.9        0.72222222 1.22222222 0.14285714 0.76923077
 0.11764706 1.54545455]

